travis:
  secure:
    BINSTAR_TOKEN: ttWknFvfiqZ+23PKghOX4Vu7bfti4AdW6SA51tEENIGMcqeHi88IvnECLSlkAA7ic09E+cGWtfc1MMeNuVBwP6VxrVM08Elbcyt94xkEYq6VAD4L2cA4QuWupDzZ2KvTh08c++pXnYghXgJJpiDW57tS9DC2Z+1gAA6/83cq4p38RrhmrucXgURlZCznOM72pzMIdLqMRnEbEwFqFm+d0CDisyAhpFKcIijqSJxyASQ1nJAqvgXerYwJyWV1lzgGt8kKCyN2gFH1t/njam12072/fK1tg2lEtgRJT+RYqteu/ZoKeEiuQmb5NGI6JAEtW3fUp6FXMQBQw7TmLoBgzrzSw9+KUl9815Njcj7/a6bfkIwfV4BuSgao+6gRo9mdWCw7pnH9YkCXAqcDSFHPQosc6r1MlnYQQe+6z/QQ/90O9rTNHxgoVU5WpmX9gPXnBaqobiH8Kq3HgcctbFz7VmAGzYaqr82mMMuOD72X2t+YTuDeoz00kQaLA29xHwh5ddhn9V4NqmZ0P47rJ9AMWFYB1VrE4uYoD7KiUU/VT0bsjjt3seCD3U7YTTTstAFAJXcVOYmojkG2iFhpgEcoTiZY87Zn4HdP1zd+HdQ7krRS7O6A1aDYOdc5is9aLqKwkdMp5moF9BKH9Ex2u5CD6Do8fGq4B5mUFTM+boXrhsY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
