travis:
  secure:
    BINSTAR_TOKEN: fwm49EjOHdij9xul+yRhz2PocYDlTSEEsm0Zw/aNmWBWE6En7UCZnPVrngc7wIyUjLmkTmucTSsw6LT1cCJZiUJm9kh5JJunCJPH/cHB4V38IanZ6sUlerpAAWZllmu1wPgEBuW2kpqlWvNEzXHMq66HjiD1RwTW0ANMyDI6iU2eytenZdqPIbYy1TA6UkdqtY4aU6WvjCIk4MBu+5ifvFkLlDioiBf6v/3Z3RcHT5CEDNad8QMy+5si2i52Qd2JROurBgcfLr4G55Igk1VTiB5Ejc8AyFc8/03u262Xs0TQR0+NjkMDRkSy8cyfUVifDv4xnLBg8nCzNR2BFrSMeqQUL4dnJCpMS9NJZSAjl+/g9fbh5tVMXFZYSDJl5iZcjjbzYaXFanXQ2+u0XNZIA5PvRjTVegenwmEBS6gFiOMb1DWF7uz4XKlVblaxsU6M7uN9YGRdWV5AArVCHyjJxW9Pi/JZof/yZMts87iaTB6PDVRHwTACOiE8CDmVB42bpavkMiba9tq8W8tSoNrAPzn+VdFmYJj1d2DzKMCVD5MTAxAeF4+prneIj0gJPmi/lShEO5v+4a1ic8Y4+1LV2iZKfWEKA7tFTdjpNScigMhhO6XqV/a2YphDxWP0mcQxa0RSYAA/iHIvt5OQfqRLlKeox8Ceem+EITte6L/D22s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
